before_install: cd website
language: node_js
node_js:
  - "10"
dist: trusty
script:
  - npm run concurrentlyScripts
install:
  - npm ci
  - npm run testBuild
cache:
  npm: true
  directories:
    - ~/.cache
branches:
  only:
    - master
env:
  CI=true