before_install: cd website
language: node_js
node_js:
  - "10"
dist: trusty
script:
  - npm run test
  - npm run ci:e2e
install:
  - npm ci
cache:
  npm: true
  directories:
    - ~/.cache
branches:
  only:
    - master
env:
  CI=true