sudo: required
language: ruby
rvm:
  - 2.5.1
addons:
  postgresql: '9.6'
branches:
  only:
    - master
before_install:
  - cd website
  - nvm install node v10.15.0
dist: trusty
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run test:coverage
  - npm run ci:e2e
  # - cd ../qit-api && rake test && cd ../website # This will need to figure out someone smarter
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
install:
  - npm ci
  - cd ../qit-api && bundle install && cd ../website
cache:
  npm: true
  directories:
    - vendor/bundle
    - ~/.cache
    - $HOME/.nvm
branches:
  only:
    - master
env:
  global:
    - CI=true
    - CC_TEST_REPORTER_ID=1576747d5c41f48a68d383c49ca2e8e7040fa13bd86ee3603f307e1885967cd3
