version: '3'

services:
  website:
    env_file: .env
    container_name: "coding-blocks-website"
    build:
      context: website
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PORT: ${WEBSITE_PORT}
    environment:
      - 'PORT=${WEBSITE_PORT}'
    ports:
      - '${WEBSITE_PORT}:${WEBSITE_PORT}'
    networks:
      - codingblocks
    restart: 'always'
    command: npm start
  db:
    container_name: "coding-blocks-database"
    build:
      context: qit-api
      dockerfile: dockerfile-postgres
    # Comment this out if you want a fresh db every time
    environment:
      - POSTGRES_USER=postgres
    ports:
     - "5432:5432"
    networks:
      - codingblocks
  web:
    container_name: "coding-blocks-api"
    build:
      context: qit-api
      dockerfile: dockerfile-ruby
    command: bundle exec rails s -p 3005 -b '0.0.0.0'
    networks:
      - codingblocks
    ports:
      - "3005:3005"
    #env_file: # You need a .env for non-dev scenario
    #  - ./qit-api/config/.env
    environment:
      - 'DOCKER=true'
      - 'QIT_API_DATABASE_USERNAME=postgres'
      - 'QIT_API_DATABASE_PASSWORD='
      - 'QIT_API_DATABASE_NAME=postgres'
      - 'QIT_API_DATABASE_HOST=coding-blocks-database'
      - 'QIT_API_SECRET=QITROCKS!'
networks:
  codingblocks:
    external: false
