version: '3'

services:
  website:
    env_file: .env
    container_name: "coding-blocks-website"
    build:
      context: website
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PORT: ${WEBSITE_PORT}
    environment:
      - 'PORT=${WEBSITE_PORT}'
    ports:
      - '${WEBSITE_PORT}:${WEBSITE_PORT}'
    networks:
      - codingblocks
    restart: 'always'
    command: npm start

networks:
  codingblocks:
    external: false
