# NOTE: THIS FILE IS FOR DEV PURPOSES ONLY!
# Nothing is secure, do not use this anywhere on the internet!
version: '3'
services:
  db:
    build:
      context: .
      dockerfile: dockerfile-postgres
    # Comment this out if you want a fresh db every time
    volumes:
      - ./tmp:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
    ports:
     - "5432:5432"
  web:
    build:
      context: .
      dockerfile: dockerfile-ruby
    command: bundle exec rails s -p 3005 -b '0.0.0.0'
    volumes:
      - .:/qit-api
    ports:
      - "3005:3005"
    #env_file: # You need a .env for non-dev scenario
    #  - ./config/.env
    environment:
      - QIT_API_DATABASE_USERNAME=postgres
      - QIT_API_DATABASE_PASSWORD=
      - QIT_API_DATABASE_NAME=postgres
      - QIT_API_DATABASE_HOST=db
      - QIT_API_SECRET=QITROCKS!