version: '3'

services:
  api:
    env_file: .env
    container_name: "coding-blocks-website"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        PORT: ${PORT}
    environment:
      - 'PORT=${PORT}'
    ports:
      - '${PORT}:${PORT}'

    networks:
      - codingblocks
    restart: 'always'
    command: npm start
networks:
  codingblocks:
    external: true
